---
- hosts: windows2019
  vars_files:
    - ./vars/ldap_auth.yml
  tasks:
    - name: Definiendo variables de entorno
      ansible.windows.win_environment:
        variables:
          JAVA_HOME: "{{ java_path }}\\"
          ALF_HOME: "{{ alfresco_base_path }}"
          ALF_DATA_HOME: "{{ alf_data_path }}"
          CATALINA_HOME: "{{ tomcat_path }}"
          LIBREOFFICE_HOME: "{{ libreoffice_path }}"
          PDFRENDERER_EXE: "{{ alfresco_base_path }}\\bin\\alfresco-pdf-renderer.exe"
          IMAGEMAGICK_EXE: "{{ imagemagick_path }}\\convert.exe"
        level: machine
    - name: Creando directorios
      ansible.windows.win_file:
        path: "{{ item }}"
        state: directory
      loop:
        - "{{ install_path }}\\installers\\tmp"
        - "{{ install_path }}\\Alfresco\\JDK11"
        - "{{ data_path }}"
        - "{{ logs_path }}"
        - "{{ tengines_path }}"
        - "{{ tomcat_path }}\\shared\\classes\\alfresco\\web-extension"
        - "{{ tomcat_path }}\\shared\\lib"
        - "{{ tomcat_path }}\\conf\\Catalina\\localhost"
        - "{{ tomcat_path }}\\shared\\classes\\alfresco\\extension"
        - "{{ alfresco_base_path }}\\logs"
        - "{{ alfresco_base_path }}\\modules\\platform"
        - "{{ alfresco_base_path }}\\modules\\share"
        - "{{ alfresco_base_path }}\\bin"
        - "{{ alfresco_base_path }}\\addons\\war"
        - "{{ alfresco_base_path }}\\addons\\share"
        - "{{ alfresco_base_path }}\\addons\\alfresco"
        - "{{ install_path }}\\nginx"
        - "{{ install_path }}\\wkhtmltopdf"
    - name: Descargando instaladores
      ansible.windows.win_get_url:
        url: "{{ item.url }}"
        dest: "{{ item.dest }} "
      loop:
        - { url: 'https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.11%2B9/OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9.zip', dest: C:\Alfresco\installers\OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9.zip }
        - { url: 'https://download.imagemagick.org/ImageMagick/download/binaries/ImageMagick-7.1.0-2-portable-Q16-x64.zip', dest: C:\Alfresco\installers\ImageMagick-7.1.0-2-portable-Q16-x64.zip }
        - { url: 'https://nginx.org/download/nginx-1.21.0.zip', dest: C:\Alfresco\installers\nginx-1.21.0.zip }
        - { url: 'https://artifacts.alfresco.com/nexus/service/local/repo_groups/public/content/org/alfresco/alfresco-pdf-renderer/1.1/alfresco-pdf-renderer-1.1-win64.tgz', dest: C:\Alfresco\installers\alfresco-pdf-renderer-1.1-win64.tgz }
        - { url: 'https://artifacts.alfresco.com/nexus/service/local/repo_groups/public/content/org/alfresco/alfresco-search-services/1.4.3.4/alfresco-search-services-1.4.3.4.zip', dest: C:\Alfresco\installers\alfresco-search-services-1.4.3.4.zip }
        - { url: 'https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox-0.12.6-1.mxe-cross-win64.7z', dest: C:\Alfresco\installers\wkhtmltox-0.12.6-1.mxe-cross-win64.7z }
    - name: Instalar NuGet
      ansible.windows.win_powershell:
        script: "Install-PackageProvider -Name NuGet -Force"
    - name: Instalar Pscx
      ansible.windows.win_powershell:
        script: "Install-Module Pscx -Scope CurrentUser -Force -AllowClobber"
    - name: Descomprimiendo PDF Renderer
      community.windows.win_unzip:
        src: C:\Alfresco\installers\alfresco-pdf-renderer-1.1-win64.tgz
        dest: c:\Alfresco\installers\tmp\
    - name: Desempaquetando PDF Renderer
      community.windows.win_unzip:
        src: C:\Alfresco\installers\tmp\alfresco-pdf-renderer-1.1-win64.tar
        dest: c:\Alfresco\installers\tmp\
    - name: Instalando PDF Renderer
      ansible.windows.win_powershell:
        script: Move-Item -Path c:\Alfresco\installers\tmp\alfresco-pdf-renderer.exe  -Destination "{{ alfresco_base_path }}\\bin\\alfresco-pdf-renderer.exe"
    - name: Desempaquetando JDK
      community.windows.win_unzip:
        src: C:\Alfresco\installers\OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9.zip
        dest: c:\Alfresco\JDK11
    - name: Instalando Tomcat
      win_package:
        path: https://downloads.apache.org/tomcat/tomcat-8/v8.5.69/bin/apache-tomcat-8.5.69.exe
        arguments: "/S /D={{ tomcat_path }}"
        state: present
    - name: Configurando Servicio de Tomcat
      win_shell: "{{ tomcat_path }}\\bin\\Tomcat8.exe //US// {{ tomcat_service_params }}"
    - name: Borrando aplicaciones default de tomcat
      ansible.windows.win_file:
        path: "{{ tomcat_path }}\\webapps"
        state: absent
    - name: Recreando directorio webapps
      ansible.windows.win_file:
        path: "{{ tomcat_path }}\\webapps"
        state: directory
    - name: Instalando LibreOffice
      win_package:
        path: https://mirrors.ucr.ac.cr/tdf/libreoffice/stable/7.1.4/win/x86_64/LibreOffice_7.1.4_Win_x64.msi
        arguments: "INSTALLLOCATION={{ libreoffice_path }} ISCHECKFORPRODUCTUPDATES=0"
        state: present
    - name: Instalando PostgreSQL
      win_package:
        path: https://get.enterprisedb.com/postgresql/postgresql-11.12-2-windows-x64.exe
        arguments: --mode unattended --prefix c:\Alfresco\PostgreSQL11
        state: present
        creates_path: c:\Alfresco\PostgreSQL11
    - name: Preparando esquema de base de datos
      ansible.windows.win_template:
        src: ./resources/create-db.sql.j2
        dest: C:\Alfresco\installers\tmp\create-db.sql
    - name: Creando base de datos alfresco
      ansible.windows.win_shell: |
        $env:PGPASSWORD = "postgres"
        C:\Alfresco\PostgreSQL11\bin\psql.exe -U postgres -f C:\Alfresco\installers\tmp\create-db.sql
    - name: Desempaquetando nginx
      community.windows.win_unzip:
        src: C:\Alfresco\installers\nginx-1.21.0.zip
        dest: c:\Alfresco\nginx
    - name: Desempaquetando Imagemagick
      community.windows.win_unzip:
        src: C:\Alfresco\installers\ImageMagick-7.1.0-2-portable-Q16-x64.zip
        dest: "{{ imagemagick_path }}"
    - name: Desempaquetando wkhtmltopdf
      community.windows.win_unzip:
        src: C:\Alfresco\installers\wkhtmltox-0.12.6-1.mxe-cross-win64.7z
        dest: c:\Alfresco\wkhtmltopdf
    - name: Desempaquetando Alfresco Search Services
      community.windows.win_unzip:
        src: C:\Alfresco\installers\alfresco-search-services-1.4.3.4.zip
        dest: "{{ install_path }}"
    - name: Descargando archivos de configuraci贸n y de aplicaci贸n
      ansible.windows.win_get_url:
        url: "{{ item.url }}"
        dest: "{{ item.dest }} "
      loop:
        - { url: 'https://downloads.loftux.net/public/content/org/alfresco/alfresco-mmt/6.0/alfresco-mmt-6.0.jar', dest: "{{ alfresco_base_path }}\\addons\\alfresco-mmt.jar" }
        - { url: 'https://artifacts.alfresco.com/nexus/service/local/repositories/releases/content/org/alfresco/content-services-community/6.2.0-ga/content-services-community-6.2.0-ga.war', dest: "{{ alfresco_base_path }}\\addons\\war\\alfresco.war" }
        - { url: 'https://artifacts.alfresco.com/nexus/service/local/repositories/releases/content/org/alfresco/share/6.2.0/share-6.2.0.war', dest: "{{ alfresco_base_path }}\\addons\\war\\share.war" }
        - { url: 'https://artifacts.alfresco.com/nexus/service/local/repositories/releases/content/org/alfresco/alfresco-share-services/6.2.0/alfresco-share-services-6.2.0.amp', dest: "{{ alfresco_base_path }}\\addons\\alfresco\\alfresco-share-services-6.2.0.amp" }
        - { url: 'https://raw.githubusercontent.com/Greencorecr/alfresco_windows/main/tomcat/catalina.properties', dest: "{{ tomcat_path }}\\conf\\catalina.properties" }
        - { url: 'https://raw.githubusercontent.com/Greencorecr/alfresco_windows/main/tomcat/tomcat-users.xml', dest: "{{ tomcat_path }}\\conf\\tomcat-users.xml" }
        - { url: 'https://raw.githubusercontent.com/Greencorecr/alfresco_windows/main/tomcat/context.xml', dest: "{{ tomcat_path }}\\conf\\context.xml" }
        - { url: 'https://jdbc.postgresql.org/download/postgresql-42.2.5.jar', dest: "{{ tomcat_path }}\\shared\\lib\\postgresql-42.2.5.jar" }
        - { url: 'https://downloads.loftux.net/public/content/org/alfresco/integrations/alfresco-googledocs-repo/3.0.4.3/alfresco-googledocs-repo-3.0.4.3.amp', dest: "{{ alfresco_base_path }}\\addons\\alfresco\\alfresco-googledocs-repo-3.0.4.3.amp" }
        - { url: 'https://downloads.loftux.net/public/content/org/alfresco/integrations/alfresco-googledocs-share/3.0.4.3/alfresco-googledocs-share-3.0.4.3.amp', dest: "{{ alfresco_base_path }}\\addons\\share\\alfresco-googledocs-share-3.0.4.3.amp" }
        - { url: 'https://downloads.loftux.net/public/content/org/alfresco/aos-module/alfresco-aos-module/1.2.2/alfresco-aos-module-1.2.2.amp', dest: "{{ alfresco_base_path }}\\addons\\alfresco\\alfresco-aos-module-1.2.2.amp" } 
        - { url: 'https://downloads.loftux.net/public/content/org/alfresco/aos-module/alfresco-vti-bin/1.2.2/alfresco-vti-bin-1.2.2.war', dest: "{{ tomcat_path }}\\webapps\_vti_bin.war" }
        - { url: 'https://downloads.loftux.net/public/content/org/alfresco/alfresco-server-root/6.0.1/alfresco-server-root-6.0.1.war', dest: "{{ tomcat_path }}\\webapps\\ROOT.war" }
    - name: Copiando archivos de configuraci贸n
      win_copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop:
        - { src: ./resources/tomcat/conf/server.xml, dest: "{{ tomcat_path }}\\conf\\server.xml" }
        - { src: ./resources/alf_data/keystore, dest: "{{ alf_data_path }}" }
        - { src: ./resources/share-config-custom.xml, dest: "{{ tomcat_path }}\\shared\\classes\\alfresco\\web-extension\\share-config-custom.xml" }
        - { src: ./resources/alfresco-search-services/solrhome, dest: "{{ ass_path }}" }
        - { src: ./resources/nginx/nginx.conf, dest: "{{ nginx_path }}\\conf\\nginx.conf" }
        - { src: ./resources/nginx/default.conf, dest: "{{ nginx_path }}\\conf\\default.conf" }
        # Certificados SSL auto-generados. Cambiar en producci贸n.
        - { src: ./resources/nginx/privkey.pem, dest: "{{ nginx_path }}\\conf\\privkey.pem" }
        - { src: ./resources/nginx/fullchain.pem, dest: "{{ nginx_path }}\\conf\\fullchain.pem" }
    - name: Copiando plantillas de configuraci贸n
      ansible.windows.win_template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop:
        - { src: ./resources/alfresco-global.properties.j2, dest: "{{ tomcat_path }}\\shared\\classes\\alfresco-global.properties" }
        - { src: ./resources/tomcat/conf/Catalina/localhost/alfresco.xml.j2, dest: "{{ tomcat_path }}\\conf\\Catalina\\localhost\\alfresco.xml" }
        - { src: ./resources/tomcat/conf/Catalina/localhost/share.xml.j2, dest: "{{ tomcat_path }}\\conf\\Catalina\\localhost\\share.xml" }
        - { src: ./resources/tomcat/conf/logging.properties.j2, dest: "{{ tomcat_path }}\\conf\\logging.properties" }
        - { src: ./resources/alfresco-search-services/solr.in.cmd.j2, dest: "{{ ass_path }}\\solr.in.cmd" }
        - { src: ./resources/limitconvert.bat.j2, dest: "{{ imagemagick_path }}\\limitconvert.bat" }
    - name: Copiando alfresco.war original a webapps
      win_copy:
        src: "{{ alfresco_base_path }}\\addons\\war\\alfresco.war"
        dest: "{{ tomcat_path }}\\webapps\\alfresco.war"
        remote_src: yes
    - name: Instalando AMPs de plataforma
      win_shell: "{{ java_path }}\\bin\\java.exe -jar {{ alfresco_base_path }}\\addons\\alfresco-mmt.jar install {{ alfresco_base_path }}\\addons\\alfresco {{ tomcat_path }}\\webapps\\alfresco.war -force -directory -nobackup"
    - name: Copiando share.war original a webapps
      win_copy:
        src: "{{ alfresco_base_path }}\\addons\\war\\share.war"
        dest: "{{ tomcat_path }}\\webapps\\share.war"
        remote_src: yes
    - name: Instalando AMPs para Share
      win_shell: "{{ java_path }}\\bin\\java.exe -jar {{ alfresco_base_path }}\\addons\\alfresco-mmt.jar install {{ alfresco_base_path }}\\addons\\share {{ tomcat_path }}\\webapps\\share.war -force -directory -nobackup"
    - name: Instala nssm para servicios
      win_chocolatey:
        name:
        - nssm
        state: present
    - name: Descargando motores de transformaci贸n
      ansible.windows.win_get_url:
        url: "{{ item.url }}"
        dest: "{{ item.dest }} "
      loop:
        - { url: 'https://artifacts.alfresco.com/nexus/service/local/repo_groups/public/content/org/alfresco/alfresco-transform-imagemagick-boot/2.5.1/alfresco-transform-imagemagick-boot-2.5.1.jar', dest: "{{ tengines_path }}\\alfresco-transform-imagemagick-boot-2.5.1.jar" }
        - { url: 'https://artifacts.alfresco.com/nexus/service/local/repo_groups/public/content/org/alfresco/alfresco-transform-libreoffice-boot/2.5.1/alfresco-transform-libreoffice-boot-2.5.1.jar', dest: "{{ tengines_path }}\\alfresco-transform-libreoffice-boot-2.5.1.jar" }
        - { url: 'https://artifacts.alfresco.com/nexus/service/local/repo_groups/public/content/org/alfresco/alfresco-transform-misc-boot/2.5.1/alfresco-transform-misc-boot-2.5.1.jar', dest: "{{ tengines_path }}\\alfresco-transform-misc-boot-2.5.1.jar" }
        - { url: 'https://artifacts.alfresco.com/nexus/service/local/repo_groups/public/content/org/alfresco/alfresco-transform-pdf-renderer-boot/2.5.1/alfresco-transform-pdf-renderer-boot-2.5.1.jar', dest: "{{ tengines_path }}\\alfresco-transform-pdf-renderer-boot-2.5.1.jar" }
        - { url: 'https://artifacts.alfresco.com/nexus/service/local/repo_groups/public/content/org/alfresco/alfresco-transform-tika-boot/2.5.1/alfresco-transform-tika-boot-2.5.1.jar', dest: "{{ tengines_path }}\\alfresco-transform-tika-boot-2.5.1.jar" }
    - name: Configurando servicios para motores de transformaci贸n
      ansible.windows.win_template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop:
        - { src: ./resources/tengines/tengine-imagemagick.bat.j2, dest: "{{ tengines_path }}\\tengine-imagemagick.bat" }
        - { src: ./resources/tengines/tengine-libreoffice.bat.j2, dest: "{{ tengines_path }}\\tengine-libreoffice.bat" }
        - { src: ./resources/tengines/tengine-misc.bat.j2, dest: "{{ tengines_path }}\\tengine-misc.bat" }
        - { src: ./resources/tengines/tengine-pdfrenderer.bat.j2, dest: "{{ tengines_path }}\\tengine-pdfrenderer.bat" }
        - { src: ./resources/tengines/tengine-tika.bat.j2, dest: "{{ tengines_path }}\\tengine-tika.bat" }
    - name: Creando servicios para motores de transformaci贸n
      community.windows.win_nssm:
        name: "{{ item.serviceName }}"
        application: "{{ tengines_path }}\\{{ item.serviceName }}.bat"
        start_mode: delayed
        display_name: "{{ item.displayName }}"
        description: "{{ item.displayName }}"
      loop:
        - { serviceName: tengine-imagemagick , displayName: " Image Magick Transformation Engine"}
        - { serviceName: tengine-libreoffice , displayName: " Libre Office Transformation Engine"}
        - { serviceName: tengine-misc , displayName: " Miscelanea Transformation Engine"}
        - { serviceName: tengine-pdfrenderer , displayName: " Pdf Renderer Transformation Engine"}
        - { serviceName: tengine-tika , displayName: " Tika Transformation Engine"}
    - name: Creando servicio para Nginx
      community.windows.win_nssm:
        name: nginx
        application: C:\Alfresco\nginx\nginx-1.21.0\nginx.exe
        start_mode: delayed
        display_name: Nginx
        description: Nginx
    - name: Creating servicio para Alfresco Search Services
      community.windows.win_nssm:
        name: alfresco-search-services
        application: "{{ ass_path }}\\solr\\bin\\solr.cmd"
        arguments: start -f
        start_mode: delayed
        display_name: Alfresco Search Services
        description: Alfresco Search Services
    - name: Descargando archivos de configuraci贸n y de aplicaci贸n
      ansible.windows.win_get_url:
        url: "{{ item.url }}"
        dest: "{{ item.dest }} "
      loop:
        - { url: 'https://repo1.maven.org/maven2/de/fmaul/javascript-console-repo/0.6/javascript-console-repo-0.6.amp', dest: "{{ install_path }}\\installers\\javascript-console-repo-0.6.amp" }
        - { url: 'https://repo1.maven.org/maven2/de/fmaul/javascript-console-share/0.6/javascript-console-share-0.6.amp', dest: "{{ install_path }}\\installers\\javascript-console-share-0.6.amp" }
    - name: Instalando AMPs para Share
      win_shell: "{{ item }}"
      loop:
        - "{{ java_path }}\\bin\\java.exe -jar {{ alfresco_base_path }}\\addons\\alfresco-mmt.jar install {{ install_path }}\\installers\\javascript-console-repo-0.6.amp {{ tomcat_path }}\\webapps\\alfresco.war -force -nobackup"
        - "{{ java_path }}\\bin\\java.exe -jar {{ alfresco_base_path }}\\addons\\alfresco-mmt.jar install {{ install_path }}\\installers\\javascript-console-share-0.6.amp {{ tomcat_path }}\\webapps\\share.war -force -nobackup"
    - name: Levantando servicios
      ansible.windows.win_service:
        name: "{{ item }}"
        state: started
      loop:
        - Tomcat8
        - alfresco-search-services
        - tengine-imagemagick
        - tengine-libreoffice
        - tengine-misc
        - tengine-pdfrenderer
        - tengine-tika
        - nginx
    - name: Abriendo Firewall TCP 80
      community.windows.win_firewall_rule:
        name: HTTP
        localport: 80
        action: allow
        direction: in
        protocol: tcp
        state: present
        enabled: yes
    - name: Abriendo Firewall TCP 443
      community.windows.win_firewall_rule:
        name: HTTPS
        localport: 443
        action: allow
        direction: in
        protocol: tcp
        state: present
        enabled: yes
    - name: Limpiando instaladores y temporales
      ansible.windows.win_file:
        path: C:\Alfresco\installers
        state: absent
