---
- hosts: windows2019
  tasks:
    - name: Defining variables
      ansible.windows.win_environment:
        variables:
          JAVA_HOME: "{{ java_path }}\\"
          ALF_HOME: "{{ alfresco_base_path }}"
          ALF_DATA_HOME: "{{ alf_data_path }}"
          CATALINA_HOME: "{{ tomcat_path }}"
        level: machine
    - name: Creando directorios
      ansible.windows.win_file:
        path: "{{ item }}"
        state: directory
      loop:
        - c:\Alfresco\installers
        - c:\Alfresco\installers\tmp
        - c:\Alfresco\JDK11
        - "{{ tomcat_path }}\\shared\\classes\\alfresco\\web-extension"
        - "{{ tomcat_path }}\\shared\\lib"
        - "{{ tomcat_path }}\\conf\\Catalina\\localhost"
        - "{{ tomcat_path }}\\shared\\classes\\alfresco\\extension"
        - "{{ alfresco_base_path }}\\logs"
        - "{{ alfresco_base_path }}\\modules\\platform"
        - "{{ alfresco_base_path }}\\modules\\share"
        - "{{ alfresco_base_path }}\\bin"
        - "{{ alfresco_base_path }}\\addons\\war"
        - "{{ alfresco_base_path }}\\addons\\share"
        - "{{ alfresco_base_path }}\\addons\\alfresco"
        - c:\Alfresco\nginx
    - name: Downloading installers
      ansible.windows.win_get_url:
        url: "{{ item.url }}"
        dest: "{{ item.dest }} "
      loop:
        - { url: 'https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.11%2B9/OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9.zip', dest: C:\Alfresco\installers\OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9.zip }
        - { url: 'https://download.imagemagick.org/ImageMagick/download/binaries/ImageMagick-7.1.0-2-portable-Q16-x64.zip', dest: C:\Alfresco\installers\ImageMagick-7.1.0-2-portable-Q16-x64.zip }
        - { url: 'https://nginx.org/download/nginx-1.21.0.zip', dest: C:\Alfresco\installers\nginx-1.21.0.zip }
        - { url: 'https://downloads.loftux.net/public/content/org/alfresco/alfresco-search-services/1.3.0.1/alfresco-search-services-1.3.0.1.zip', dest: C:\Alfresco\installers\alfresco-search-services-1.3.0.1.zip }
    - name: Unarchive JDK
      community.windows.win_unzip:
        src: C:\Alfresco\installers\OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9.zip
        dest: c:\Alfresco\JDK11
    - name: Install Tomcat
      win_package:
        path: https://downloads.apache.org/tomcat/tomcat-8/v8.5.68/bin/apache-tomcat-8.5.68.exe
        arguments: "/S /D={{ tomcat_path }}"
        state: present
    - name: Increase JVM memory size
      win_shell: "{{ tomcat_path }}\\bin\\Tomcat8.exe //US// {{ tomcat_service_params }}"
    - name: Borrando aplicaciones default de tomcat
      ansible.windows.win_file:
        path: "{{ tomcat_path }}\\webapps"
        state: absent
    - name: Recreando directorio webapps
      ansible.windows.win_file:
        path: "{{ tomcat_path }}\\webapps"
        state: directory
    - name: Installs Libreoffice from MSI
      win_package:
        path: https://mirrors.ucr.ac.cr/tdf/libreoffice/stable/7.1.4/win/x86_64/LibreOffice_7.1.4_Win_x64.msi
        state: present
    - name: Installs Pgsql
      win_package:
        path: https://get.enterprisedb.com/postgresql/postgresql-11.12-2-windows-x64.exe
        arguments: --mode unattended --prefix c:\Alfresco\PostgreSQL11
        state: present
        creates_path: c:\Alfresco\PostgreSQL11
    - name: Prepare db creation template
      ansible.windows.win_template:
        src: ./resources/create-db.sql.j2
        dest: C:\Alfresco\installers\tmp\create-db.sql
    - name: Create alfresco database
      ansible.windows.win_shell: |
        $env:PGPASSWORD = "postgres"
        C:\Alfresco\PostgreSQL11\bin\psql.exe -U postgres -f C:\Alfresco\installers\tmp\create-db.sql
    - name: Delete db creation template
      ansible.windows.win_file:
        path: C:\Alfresco\installers\tmp\create-db.sql
        state: absent
    - name: Unarchive nginx
      community.windows.win_unzip:
        src: C:\Alfresco\installers\nginx-1.21.0.zip
        dest: c:\Alfresco\nginx
    - name: Unarchive Imagemagick
      community.windows.win_unzip:
        src: C:\Alfresco\installers\ImageMagick-7.1.0-2-portable-Q16-x64.zip
        dest: c:\Alfresco\ImageMagick
    - name: Unarchive solr6
      community.windows.win_unzip:
        src: C:\Alfresco\installers\alfresco-search-services-1.3.0.1.zip
        dest: c:\Alfresco\alfresco
    - name: Renaming a-s-s to solr6
      win_shell: rename-item alfresco-search-services solr6
      args:
        chdir: C:\Alfresco\alfresco
        creates: C:\Alfresco\alfresco\solr6
    - name: Downloading config files
      ansible.windows.win_get_url:
        url: "{{ item.url }}"
        dest: "{{ item.dest }} "
      loop:
        - { url: 'https://downloads.loftux.net/public/content/org/alfresco/alfresco-mmt/6.0/alfresco-mmt-6.0.jar', dest: "{{ alfresco_base_path }}\\addons\\alfresco-mmt.jar" }
        - { url: 'https://github.com/Greencorecr/alfresco_windows/raw/main/tomcat/alfresco-pdf-renderer', dest: "{{ alfresco_base_path }}\\bin\\alfresco-pdf-renderer" }
        - { url: 'https://artifacts.alfresco.com/nexus/service/local/repositories/releases/content/org/alfresco/content-services-community/6.2.0-ga/content-services-community-6.2.0-ga.war', dest: "{{ alfresco_base_path }}\\addons\\war\\alfresco.war" }
        - { url: 'https://artifacts.alfresco.com/nexus/service/local/repositories/releases/content/org/alfresco/share/6.2.0/share-6.2.0.war', dest: "{{ alfresco_base_path }}\\addons\\war\\share.war" }
        - { url: 'https://artifacts.alfresco.com/nexus/service/local/repositories/releases/content/org/alfresco/alfresco-share-services/6.2.0/alfresco-share-services-6.2.0.amp', dest: "{{ alfresco_base_path }}\\addons\\alfresco\\alfresco-share-services-6.2.0.amp" }
        - { url: 'https://raw.githubusercontent.com/Greencorecr/alfresco_windows/main/tomcat/catalina.properties', dest: "{{ tomcat_path }}\\conf\\catalina.properties" }
        - { url: 'https://raw.githubusercontent.com/Greencorecr/alfresco_windows/main/tomcat/tomcat-users.xml', dest: "{{ tomcat_path }}\\conf\\tomcat-users.xml" }
        - { url: 'https://raw.githubusercontent.com/Greencorecr/alfresco_windows/main/tomcat/context.xml', dest: "{{ tomcat_path }}\\conf\\context.xml" }
        - { url: 'https://jdbc.postgresql.org/download/postgresql-42.2.5.jar', dest: "{{ tomcat_path }}\\shared\\lib\\postgresql-42.2.5.jar" }
        - { url: 'https://raw.githubusercontent.com/Greencorecr/alfresco_windows/main/search/shared.properties', dest: C:\Alfresco\alfresco\solr6\solrhome\conf\shared.properties } 
        - { url: 'https://downloads.loftux.net/public/content/org/alfresco/integrations/alfresco-googledocs-repo/3.0.4.3/alfresco-googledocs-repo-3.0.4.3.amp', dest: "{{ alfresco_base_path }}\\addons\\alfresco\\alfresco-googledocs-repo-3.0.4.3.amp" }
        - { url: 'https://downloads.loftux.net/public/content/org/alfresco/integrations/alfresco-googledocs-share/3.0.4.3/alfresco-googledocs-share-3.0.4.3.amp', dest: "{{ alfresco_base_path }}\\addons\\share\\alfresco-googledocs-share-3.0.4.3.amp" }
        - { url: 'https://downloads.loftux.net/public/content/org/alfresco/aos-module/alfresco-aos-module/1.2.2/alfresco-aos-module-1.2.2.amp', dest: "{{ alfresco_base_path }}\\addons\\alfresco\\alfresco-aos-module-1.2.2.amp" } 
        - { url: 'https://downloads.loftux.net/public/content/org/alfresco/aos-module/alfresco-vti-bin/1.2.2/alfresco-vti-bin-1.2.2.war', dest: "{{ tomcat_path }}\\webapps\_vti_bin.war" }
        - { url: 'https://downloads.loftux.net/public/content/org/alfresco/alfresco-server-root/6.0.1/alfresco-server-root-6.0.1.war', dest: "{{ tomcat_path }}\\webapps\\ROOT.war" }
        - { url: 'https://raw.githubusercontent.com/Greencorecr/alfresco_windows/main/nginx/nginx.conf', dest: C:\Alfresco\nginx\nginx.conf }
        - { url: 'https://raw.githubusercontent.com/Greencorecr/alfresco_windows/main/nginx/default', dest: C:\Alfresco\nginx\default }
    - name: Copy config files
      win_copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop:
        - { src: ./resources/tomcat/conf/server.xml, dest: "{{ tomcat_path }}\\conf\\server.xml" }
        - { src: ./resources/alf_data/keystore, dest: "{{ alf_data_path }}" }
        - { src: ./resources/share-config-custom.xml, dest: "{{ tomcat_path }}\\shared\\classes\\alfresco\\web-extension\\share-config-custom.xml" }
    - name: Copy config templates
      ansible.windows.win_template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop:
        - { src: ./resources/alfresco-global.properties.j2, dest: "{{ tomcat_path }}\\shared\\classes\\alfresco-global.properties" }
        - { src: ./resources/tomcat/conf/Catalina/localhost/alfresco.xml.j2, dest: "{{ tomcat_path }}\\conf\\Catalina\\localhost\\alfresco.xml" }
        - { src: ./resources/tomcat/conf/Catalina/localhost/share.xml.j2, dest: "{{ tomcat_path }}\\conf\\Catalina\\localhost\\share.xml" }
    - name: Copy vanilla alfresco.war to webapps
      win_copy:
        src: "{{ alfresco_base_path }}\\addons\\war\\alfresco.war"
        dest: "{{ tomcat_path }}\\webapps\\alfresco.war"
        remote_src: yes
    - name: Install platform AMPs
      win_shell: "{{ java_path }}\\bin\\java.exe -jar {{ alfresco_base_path }}\\addons\\alfresco-mmt.jar install {{ alfresco_base_path }}\\addons\\alfresco {{ tomcat_path }}\\webapps\\alfresco.war -force -directory -nobackup"
    - name: Copy vanilla share.war to webapps
      win_copy:
        src: "{{ alfresco_base_path }}\\addons\\war\\share.war"
        dest: "{{ tomcat_path }}\\webapps\\share.war"
        remote_src: yes
    - name: Install Share AMPs
      win_shell: "{{ java_path }}\\bin\\java.exe -jar {{ alfresco_base_path }}\\addons\\alfresco-mmt.jar install {{ alfresco_base_path }}\\addons\\share {{ tomcat_path }}\\webapps\\share.war -force -directory -nobackup"
    - name: Instala nssm para servicios
      win_chocolatey:
        name:
        - nssm
        state: present
    - name: Creating service for Tomcat
      ansible.windows.win_service:
        name: tomcat
        path: "{{ java_path }}\\bin\\startup.bat"
        description: Apache Tomcat for Alfresco
    # Tomcat no funciona desde servicio, solo manual. TODO: Arreglar.
    # "service.bat install Tomcat8" también falla.
    - name: Creating service for Nginx
      community.windows.win_nssm:
        name: nginx
        application: C:\Alfresco\nginx\nginx-1.21.0\nginx.exe
        description: Nginx
    - name: Starting up Nginx
      ansible.windows.win_service:
        name: nginx
        state: started

# TODO, crear servicios
# sudo curl -s -o /etc/systemd/system/alfresco-search.service $BASE_DOWNLOAD/search/alfresco-search.service

# TODO, traducir scripts
# sudo curl -s -o $ALF_HOME/solr6/solr.in.sh $BASE_DOWNLOAD/search/solr.in.sh
# sudo $ALF_HOME/addons/apply.sh all
# sudo curl -s -o $ALF_HOME/addons/apply.sh $BASE_DOWNLOAD/scripts/apply.sh
# sudo curl -s -o $ALF_HOME/alfresco-service.sh $BASE_DOWNLOAD/scripts/alfresco-service.sh
# sudo sed -i "s/@@LOCALESUPPORT@@/$LOCALESUPPORT/g" $ALF_HOME/alfresco-service.sh 
# sudo curl -s -o $ALF_HOME/scripts/limitconvert.sh $BASE_DOWNLOAD/scripts/limitconvert.sh
