---
- hosts: windows2019
  tasks:
    - name: Creando directorio para instaladores
      ansible.windows.win_file:
        path: c:\Alfresco\installers
        state: directory
    - name: Dir para Alfresco
      ansible.windows.win_file:
        path: c:\Alfresco\alfresco\alf_data
        state: directory
    - name: Dir para Catalina
      ansible.windows.win_file:
        path: c:\Alfresco\alfresco\tomcat
        state: directory
    - name: Dir para Logs
      ansible.windows.win_file:
        path: c:\Alfresco\alfresco\logs
        state: directory
    - name: JAVA_HOME
      ansible.windows.win_environment:
        state: present
        name: JAVA_HOME
        value: c:\Alfresco\JDK11\jdk-11.0.11+9\
        level: machine
    - name: ALF_HOME
      ansible.windows.win_environment:
        state: present
        name: ALF_HOME
        value: c:\Alfresco\alfresco
        level: machine
    - name: ALF_DATA_HOME
      ansible.windows.win_environment:
        state: present
        name: ALF_DATA_HOME
        value: c:\Alfresco\alfresco\alf_data
        level: machine
    - name: CATALINA_HOME
      ansible.windows.win_environment:
        state: present
        name: CATALINA_HOME
        value: c:\Alfresco\alfresco\tomcat
        level: machine
    - name: Borrando aplicaciones default de tomcat
      ansible.windows.win_file:
        path: c:\Alfresco\alfresco\tomcat\webapps
        state: absent
    - name: Recreando directorio webapps
      ansible.windows.win_file:
        path: c:\Alfresco\alfresco\tomcat\webapps
        state: directory
    - name: Creando directorio para conf de tomcat
      ansible.windows.win_file:
        path: c:\Alfresco\alfresco\tomcat\conf\Catalina\localhost
        state: directory
    - name: Download Tomcat conf server.xml
      ansible.windows.win_get_url:
        url: https://raw.githubusercontent.com/Greencorecr/alfresco_windows/main/tomcat/server.xml
        dest: C:\Alfresco\alfresco\tomcat\conf\server.xml
    - name: Download Tomcat conf catalina.properties
      ansible.windows.win_get_url:
        url: https://raw.githubusercontent.com/Greencorecr/alfresco_windows/main/tomcat/catalina.properties
        dest: C:\Alfresco\alfresco\tomcat\conf\catalina.properties
    - name: Download Tomcat conf tomcat-users.xml
      ansible.windows.win_get_url:
        url: https://raw.githubusercontent.com/Greencorecr/alfresco_windows/main/tomcat/tomcat-users.xml
        dest: C:\Alfresco\alfresco\tomcat\conf\tomcat-users.xml
    - name: Download Tomcat conf context.xml
      ansible.windows.win_get_url:
        url: https://raw.githubusercontent.com/Greencorecr/alfresco_windows/main/tomcat/context.xml
        dest: C:\Alfresco\alfresco\tomcat\conf\context.xml
    - name: Creando /shared extension
      ansible.windows.win_file:
        path: c:\Alfresco\alfresco\tomcat\shared\classes\alfresco\extension
        state: directory
    - name: Creando /shared web-extension
      ansible.windows.win_file:
        path: c:\Alfresco\alfresco\tomcat\shared\classes\alfresco\web-extension
        state: directory
    - name: Creando /shared lib
      ansible.windows.win_file:
        path: c:\Alfresco\alfresco\tomcat\shared\lib
        state: directory
    - name: Download Global Properties
      ansible.windows.win_get_url:
        url: https://raw.githubusercontent.com/Greencorecr/alfresco_windows/main/tomcat/alfresco-global.properties
        dest: C:\Alfresco\alfresco\tomcat\shared\classes\alfresco-global.properties
    - name: Download Share Config
      ansible.windows.win_get_url:
        url: https://raw.githubusercontent.com/Greencorecr/alfresco_windows/main/tomcat/share-config-custom.xml
        dest: C:\Alfresco\alfresco\tomcat\shared\classes\alfresco\web-extension\
    - name: Download JDBC for PostgreSQL
      ansible.windows.win_get_url:
        url: https://jdbc.postgresql.org/download/postgresql-42.2.5.jar
        dest: C:\Alfresco\alfresco\tomcat\lib\
    - name: Download Imagemagick
      ansible.windows.win_get_url:
        url: https://download.imagemagick.org/ImageMagick/download/binaries/ImageMagick-7.1.0-2-portable-Q16-x64.zip
        dest: C:\Alfresco\installers\ImageMagick-7.1.0-2-portable-Q16-x64.zip
    - name: Unarchive Imagemagick
      community.windows.win_unzip:
        src: C:\Alfresco\installers\ImageMagick-7.1.0-2-portable-Q16-x64.zip
        dest: c:\Alfresco\ImageMagick



          #  sudo curl -s -o /etc/nginx/nginx.conf $BASE_DOWNLOAD/nginx/nginx.conf
          #  sudo curl -c 5 /etc/nginx/conf.d/alfresco.conf $BASE_DOWNLOAD/nginx/default


          #sudo mv $JDBCPOSTGRES $CATALINA_HOME/lib

          # TODO, crear servicios

#    sudo curl -s -o $ALF_HOME/alfresco-service.sh $BASE_DOWNLOAD/scripts/alfresco-service.sh
#    sudo chmod 755 $ALF_HOME/alfresco-service.sh
#    sudo sed -i "s/@@LOCALESUPPORT@@/$LOCALESUPPORT/g" $ALF_HOME/alfresco-service.sh 
#    # Enable the service
#    sudo systemctl enable alfresco.service
#    sudo systemctl daemon-reload

# Las siguientes líneas que dicen #listo#, necesitan un condicional para que no se ejecuten 2 veces.

    - name: Libreoffice from MSI
      win_package:
        path: https://mirrors.ucr.ac.cr/tdf/libreoffice/stable/7.1.4/win/x86_64/LibreOffice_7.1.4_Win_x64.msi
        state: present
    - name: Dir para JDK
      ansible.windows.win_file:
        path: c:\Alfresco\JDK11
        state: directory
    - name: Download JDK
      ansible.windows.win_get_url:
        url: https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.11%2B9/OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9.zip
        dest: C:\Alfresco\installers\OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9.zip
    - name: Unarchive JDK
      community.windows.win_unzip:
        src: C:\Alfresco\installers\OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9.zip
        dest: c:\Alfresco\JDK11
    - name: Pgsql
      win_package:
        path: https://get.enterprisedb.com/postgresql/postgresql-11.12-2-windows-x64.exe
        arguments: --mode unattended --prefix c:\Alfresco\PostgreSQL11
        state: present
  
  
    - name: Dir para nginx
      ansible.windows.win_file:
        path: c:\Alfresco\nginx
        state: directory
    - name: Download nginx
      ansible.windows.win_get_url:
        url: https://nginx.org/download/nginx-1.21.0.zip
        dest: C:\Alfresco\installers\nginx-1.21.0.zip
    - name: Unarchive nginx
      community.windows.win_unzip:
        src: C:\Alfresco\nginx-1.21.0.zip
        dest: c:\Alfresco\installers\nginx

# Se queda pegado y no hace nada. Falta forzarlo a que sea interactivo
#fallo#
#fallo#  - name: Tomcat
#fallo#    win_package:
#fallo#      path: https://downloads.apache.org/tomcat/tomcat-8/v8.5.68/bin/apache-tomcat-8.5.68.exe
#fallo#        #arguments: "/S" #/D=C:\Alfresco\Tomcat
#fallo#      state: present


    # apache-tomcat-8.5.11.exe /S /D=D:\softwares\Tomcat
    
#    - name: Instalar dependencias para Alfresco - nginx
#      win_chocolatey:
#        name:
#        - nginx
#        state: present
#        install_args: '/D=C:\Alfresco\nginx'
#          #    - name: Instala firefox
#          #      win_chocolatey:
#          #        name:
#          #        - firefox # solo para debug
#          #        state: present
#          #
