name: Instalar Alfresco en CI
# 1. Instalar WSL1 y Ubuntu, e instalar ansible
# 2. Ejecutar receta de ansible

on: 
  push

jobs:
  ansible_install:
    name: Instalar WSL1 y Ubuntu
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      - name: Habilita WSL
        shell: powershell
        run: Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
#      - name: Habilita Virt para WSL
#        shell: powershell
#        run: Enable-WindowsOptionalFeature -Online -FeatureName VirtualMachinePlatform
      - name: Crea directorios para instaladores
        shell: powershell
        run: New-Item -Path "c:\" -name "Alfresco\installers\" -ItemType "directory"
      - name: Descarga Ubuntu
        shell: powershell
        run: Invoke-WebRequest -Uri https://aka.ms/wslubuntu2004 -OutFile c:\Alfresco\installers\Ubuntu.zip -UseBasicParsing
      - name: Desempaqueta Ubuntu
        shell: powershell
        run: Expand-Archive c:\Alfresco\installers\Ubuntu.zip
